const { shell, esc, money, EMAIL } = require('./render');
const { productPath } = require('./catalogue');
const copy = require('./content');
const paths = ['/delivery', '/returns', '/contact', '/guides/junior-racket-size', '/guides/tennis-grips'];
function informationPage(path, { products, settings }) {
  const link = (sku, label) => { const product = products.find(p => p.sku === sku); return product ? `<a href="${esc(productPath(product))}">${esc(label || copy.title(product))}</a>` : '<a href="/shop">Browse current products</a>'; };
  const email = `<a href="mailto:${EMAIL}">${EMAIL}</a>`;
  let title, description, body;
  if (path === '/delivery') {
    title = 'New Zealand Delivery & Pickup';
    description = 'See current NZ courier and pickup options for Kim Jones Coaching shop orders, and how to check timing for products available to order.';
    body = `<p>Shop orders are priced in New Zealand dollars. Choose your fulfilment option in the cart to see the delivery charge before proceeding to payment.</p><h2>Current delivery options</h2><ul><li><strong>Pickup: free.</strong> ${esc(settings.pickup_label || 'Pickup from coaching / club')}. ${esc(settings.pickup_instructions || 'Arrange the collection time and location with Kim.')}</li>${settings.local_delivery_enabled ? `<li><strong>Local delivery: ${money(settings.local_delivery_fee)}.</strong> Confirm with Kim that your address is within the local delivery area before choosing this option.</li>` : ''}${settings.courier_delivery_enabled ? `<li><strong>NZ courier: ${money(settings.courier_delivery_fee)} per order.</strong>${Number(settings.free_shipping_threshold) > 0 ? ` Free courier delivery for qualifying product totals of ${money(settings.free_shipping_threshold)} or more.` : ''}</li>` : ''}</ul><h2>Stock and timing</h2><p>“In stock” means the shop currently records stock on hand. “Available to order” means the item is sourced for your order and is not a promise of immediate dispatch. Ask Kim to confirm availability and timing before paying if you need your gear by a specific date.</p><p>For rural addresses, oversized items or a mixed order containing both stocked and sourced items, contact Kim before ordering to confirm the delivery arrangements. Dispatch and arrival dates need to be confirmed for your order.</p><h2>Racket services</h2><p>Racket stringing requires a physical racket. Confirm drop-off, collection and string choice with Kim; ordering labour does not include a new racket or a courier collection service.</p><p>For delivery help, email ${email} with the product code and your town or postcode.</p><p><a href="/shop">Back to the shop</a> · <a href="/returns">Returns & order help</a></p>`;
  } else if (path === '/returns') {
    title = 'Returns & Order Help';
    description = 'Contact Kim Jones Coaching about faulty goods, delivery problems, returns and product questions. Your New Zealand consumer rights apply.';
    body = `<p>For help with a shop order, email ${email}. Include your order reference, the product and a description of the issue. For a damaged or incorrect item, photos can help us understand what happened.</p><h2>Faulty goods and your rights</h2><p>Your rights under New Zealand’s Consumer Guarantees Act apply to eligible consumer purchases. If goods are faulty, do not match their description or fail an applicable guarantee, the remedy may be a repair, replacement or refund, depending on the circumstances. Nothing on this page limits those rights.</p><p>Contact Kim so the problem and appropriate remedy can be assessed. Agree on the return arrangements before sending an item back.</p><h2>Changing your mind or choosing a different size</h2><p>Contact Kim before ordering if you are unsure about racket size, grip size, pack quantity or accessory compatibility. A change-of-mind return is different from a faulty-goods claim; ask Kim whether a return or exchange can be accepted and on what terms.</p><h2>Delivery and order questions</h2><p>If your parcel has not arrived, your order is incorrect, or you need to change an order, email Kim with your order reference. For products marked “available to order”, confirm the expected timing before purchase.</p><p>Read more about <a href="https://www.consumerprotection.govt.nz/general-help/consumer-laws/consumer-guarantees-act">New Zealand consumer guarantees</a> and <a href="https://www.consumerprotection.govt.nz/general-help/common-consumer-issues/change-of-mind">change-of-mind purchases</a> on Consumer Protection.</p><p><a href="/delivery">Delivery information</a> · <a href="/shop">Back to the shop</a></p>`;
  } else if (path === '/contact') {
    title = 'Contact Kim About Gear & Orders';
    description = 'Ask Kim Jones Coaching about tennis and pickleball equipment, product sizes, NZ delivery, stock availability or an existing shop order.';
    body = `<p>Kim Jones Coaching Limited supplies tennis and pickleball equipment through this shop.</p><p><strong>Email:</strong> ${email}</p><h2>Help choosing gear</h2><p>Send the product name or code and what you would like to check. For a junior racket, the player’s height, current racket length and playing experience are useful starting points. Confirm the supplied grip size, colour and pack quantity if these are important to your choice.</p><h2>Stock and delivery</h2><p>Tell Kim your town or postcode and any date you need the item by. Products labelled “available to order” need an availability and timing check.</p><h2>Existing orders</h2><p>Include your order reference and a brief explanation of the issue. Please do not email card details.</p><p><a href="/delivery">Delivery & pickup</a> · <a href="/returns">Returns & order help</a> · <a href="/booking">Book coaching</a></p>`;
  } else if (path === '/guides/junior-racket-size') {
    title = 'Choosing a Junior Tennis Racket';
    description = 'Compare junior tennis racket length, weight and grip size before buying. Use manufacturer age guides as a starting point and check the fit with Kim.';
    body = `<p>Start with the player, then compare the racket specifications. A junior model’s length, weight and grip size are more useful buying details than its colour or the name of an adult model it resembles.</p><h2>What to check before choosing</h2><ul><li><strong>Length:</strong> check the length in inches against the player’s current racket and the manufacturer’s guide.</li><li><strong>Weight:</strong> notice whether the listed weight includes strings. Compare like with like.</li><li><strong>Grip:</strong> confirm the exact grip size supplied; a supplier’s full range does not mean every size is available here.</li><li><strong>Playing experience:</strong> a player moving up from a smaller racket may need a fit check before changing length and weight together.</li></ul><h2>Age guides are a starting point</h2><p>Manufacturer guides can differ. For example, HEAD lists the IG Gravity Jr 26 with a 9–11 age guide, while Yonex’s junior range pairs ages with height ranges. Use the guide for the specific model and ask for help if the player falls between sizes.</p><h2>A 26-inch option to compare</h2><p>${link('2312057')} has a listed length of 26 inches and unstrung weight of 250 g. Open the product page for its current availability and specifications. Confirm the supplied grip size before ordering.</p><p><a class="btn btn-primary" href="/shop/junior-tennis-rackets">Browse junior rackets</a></p><h2>Ask Kim before ordering</h2><p>Share the player’s height, current racket length and playing experience with ${email}. If you can bring the current racket to a lesson, arrange a fit discussion with Kim.</p><p>Manufacturer references: <a href="https://headracquets.co.nz/products/25-head-ig-gravity-jr-26-tennis-racquet-l07">HEAD IG Gravity Jr 26</a> and <a href="https://www.yonex.com/tennis-yonex-junior-racquets">Yonex junior racket guide</a>.</p>`;
  } else if (path === '/guides/tennis-grips') {
    title = 'Tennis Overgrip or Replacement Grip?';
    description = 'Understand the difference between a tennis overgrip and a replacement grip, check pack quantities and find grips in the Kim Jones Coaching shop.';
    body = `<p>Check which layer of your racket handle you want to replace before adding a grip to your cart. An overgrip and a replacement grip do different jobs.</p><h2>The two grip types</h2><table><thead><tr><th>Type</th><th>What you are buying</th></tr></thead><tbody><tr><th>Replacement grip</th><td>The base grip around the racket handle. Check its material and thickness.</td></tr><tr><th>Overgrip</th><td>A thinner outer wrap fitted over the existing base grip. Remove the old overgrip before fitting the new one.</td></tr></tbody></table><h2>Check feel and pack quantity</h2><p>Grips come in different materials and finishes. Check the exact range name and the quantity in the listing; a three-pack and a single grip should not be compared on pack price alone.</p><p>${link('MT-B')} is one pack containing three blue overgrips. Check current availability on the product page. Small accessories can be combined in a single order, with the total delivery charge shown in the cart.</p><h2>When to replace an overgrip</h2><p>How often you replace it depends on use. Check for wear and changes in feel instead of assuming a fixed replacement schedule. Follow the pack’s fitting instructions, keep the wrap tension consistent and secure the end with finishing tape.</p><p><a class="btn btn-primary" href="/shop/tennis-grips">Browse grips & overgrips</a></p><p>For fitting detail, see <a href="https://www.head.com/rs/stories/how-to-change-your-tennis-overgrip">HEAD’s tennis overgrip guide</a>. If you are unsure which product to order, email ${email}.</p>`;
  } else return null;
  return shell({title, description, canonical: path, body: `<section class="section"><div class="container shop-copy"><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/shop">Shop</a></nav><h1>${title}</h1>${body}</div></section>`});
}
module.exports = { paths, informationPage };
